✅ [unit] fix random warning/failure (#170)
* :white_check_mark: [unit] ensure that global objects are always clean

fix ''getInternalContext' not yet available, please call '.init()' first.' warning

* :white_check_mark: [unit] stop spec execution on failure/pending

cf https://github.com/jasmine/jasmine/issues/1579, when marking a spec as pending in before each without `oneFailurePerSpec`, spec will continue its execution silently.
this behavior generated random failure due to inconsistent state:
```
logger session
    ✗ should renew on activity after expiration
	Unable to get property 'notify' of undefined or null reference thrown

	Unable to get property 'notify' of undefined or null reference thrown

	Unable to get property 'notify' of undefined or null reference thrown

	Unable to get property 'notify' of undefined or null reference thrown

	Error: Mock clock is not installed, use jasmine.clock().install()
	    at <Jasmine>
	   at Anonymous function (eval code:17:9)
	    at <Jasmine>
```

* trigger ci