replay: add dd-privacy attribute for obfuscation & ignoring input (#715)
* recorder: introduce helpers to obfuscate elements

Adds the nodeIsHidden & nodeOrAncestorsAreHidden helpers.

These helpers, part of the new "privacy" file, replace rrweb's
isBlocked() and rrweb-snapshot's _isBlockedElement() functions.

They do not rely on the blockClass variable (removed in a later
commit), but instead use constants defined within the same file.

An element is considered hidden if it has the data attribute
"data-dd-privacy" set to "hidden" or a class of "dd-privacy-hidden".

* recorder: introduce helpers to ignore input

Adds the nodeHasInputIngored & nodeOrAncestorsHaveInputIngnored
helpers.

These helpers will return true when a node should have it's input
ignored, either because an attribute/class is set, or because it's a
kind of input we don't want to track.

They do not rely on the ignoreClass variable (removed in a later
commit), but instead use constants defined within the same file.

An element is considered ignored if it has the data attribute
"data-dd-privacy" set to "input-ignored", a class of
"dd-privacy-input-ingored", or a type of "email", "password" or "tel".

* recorder: add unit tests for obfuscation & input ignore

* e2e: update appium version

Calls to setValue() would fail with 1.9.1:

	Error: invalid argument: 'value' must be a list
	  (Session info: chrome=86.0.4240.198)
	  (Driver info: chromedriver=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}),platform=Linux 4.1.13-101.fc21.x86_64 x86_64)

* recorder: add e2e tests for obfuscation & input ignore

* recorder: remove unused variables

blockClass, blockSelector, and ignoreClass are now unused

* recorder: rename helpers

Renames:
- nodeIsHidden to nodeShouldBeHidden
- nodeOrAncestorsAreHidden to nodeOrAncestorsShouldBeHidden
- nodeHasInputIngored to nodeShouldHaveInputIngored
- nodeOrAncestorsHaveInputIngnored to nodeOrAncestorsShouldHaveInputIngnored

* recorder: rename ElementNode's needBlock to shouldBeHidden